function posthoc
    dsAnalyze(pwd, ... 
        {@gvFRsoma, @gvCalcPower}, ... %{@gvlowval, @gvPLVs, @gvPLVlow},... %@gvPLVD1, @gvPLVlowD1, @gvPLVD2, @gvPLVlowD2},... %{@gvPLVD1}, ...
    'load_all_data_flag',1, 'overwrite_flag',0, 'verbose_flag',1, 'parfor_flag',0, 'save_results_flag',1,'close_fig_flag',1,'cluster_flag',1,'sims_per_job',5, 'cluster_matlab_version', '2017b');
end