function [Y,T] = odefun_20150527_201213
tspan=[0 4000]; dt=0.005;
T=tspan(1):dt:tspan(2); nstep=length(T);
fileID = 1; nreports = 5; enableLog = 1:(nstep-1)/nreports:nstep;enableLog(1) = [];
fprintf('\nSimulation interval: %g-%g\n',tspan);fprintf('Starting integration (euler, dt=%g)\n',dt);soma_soma_iSYN_width = inf;
soma_soma_iSYN_Nmax = max((2),(2));
soma_soma_iSYN_srcpos = linspace(1,soma_soma_iSYN_Nmax,(2))'*ones(1,(2));
soma_soma_iSYN_dstpos = (linspace(1,soma_soma_iSYN_Nmax,(2))'*ones(1,(2)))';
soma_soma_iSYN_netcon = rand((2),(2))<0;;
dend_soma_iCOM_compcon = eye((2),(2));
dend_iMultiPoissonExp_Ge = multi_Poisson((2), (127), (2), (10), (1), 2, .5, (2000), (0.005));
dend_iMultiPoissonExp_Gi = multi_Poisson((2), (73), (2), (10), (1), 5, .5, (2000), (0.005));
soma_dend_iCOM_compcon = eye((2),(2));
dend_dend_iGAP_UB = max((2),(2));
dend_dend_iGAP_Xpre = linspace(1,dend_dend_iGAP_UB,(2))'*ones(1,(2));
dend_dend_iGAP_Xpost = (linspace(1,dend_dend_iGAP_UB,(2))'*ones(1,(2)))';
dend_dend_iGAP_mask = rand((2),(2))<0;
soma_golomb_K_ainf = @(soma_v) 1./(1+exp(-(soma_v+50)./20));
soma_golomb_K_binf = @(soma_v) 1./(1+exp(-(soma_v+70)./-6));
soma_golomb_K_id = @(soma_v,soma_golomb_K_a,soma_golomb_K_b) (1.8).*(soma_golomb_K_a.^3).*soma_golomb_K_b.*(soma_v-(-90));
soma_golomb_Kdr_ninf = @(soma_v) 1./(1+exp(-(soma_v+12.4)./6.8));
soma_golomb_Kdr_taun = @(soma_v) (0.087+11.4./(1+exp((soma_v+14.6)./8.6))) .* (0.087+11.4./(1+exp(-(soma_v-1.3)./18.7)));
soma_golomb_Kdr_ikdr = @(soma_v,soma_golomb_Kdr_n) (225).*(soma_golomb_Kdr_n.^2).*(soma_v-(-90));
soma_golomb_Na_minf = @(soma_v) 1./(1+exp(-(soma_v-(-24))./11.5));
soma_golomb_Na_hinf = @(soma_v) 1./(1+exp(-(soma_v+58.3)./-6.7));
soma_golomb_Na_tauh = @(soma_v) 0.5 + 14./(1+exp(-(soma_v+60)./-12));
soma_golomb_Na_ina = @(soma_v,soma_golomb_Na_h) (112.5).*soma_golomb_Na_h.*((1./(1+exp(-(soma_v-(-24))./11.5))).^3).*(soma_v-(50));
soma_leak_ileak = @(soma_v) (0.03)*(soma_v-(-54.4));
soma_soma_iSYN_ISYN = @(V,soma_soma_iSYN_s) ((0.5).*(soma_soma_iSYN_netcon*soma_soma_iSYN_s).*(V-(0)));
dend_soma_iCOM_dV = @(IN,OUT) ((IN*ones(1,size(IN,1)))'-(OUT*ones(1,size(OUT,1))));
dend_soma_iCOM_ICOM = @(IN,OUT) (0.15).*sum((((IN*ones(1,size(IN,1)))'-(OUT*ones(1,size(OUT,1))))).*dend_soma_iCOM_compcon,2);
dend_golomb_K_ainf = @(dend_v) 1./(1+exp(-(dend_v+50)./20));
dend_golomb_K_binf = @(dend_v) 1./(1+exp(-(dend_v+70)./-6));
dend_golomb_K_id = @(dend_v,dend_golomb_K_a,dend_golomb_K_b) (0.18).*(dend_golomb_K_a.^3).*dend_golomb_K_b.*(dend_v-(-90));
dend_golomb_Kdr_ninf = @(dend_v) 1./(1+exp(-(dend_v+12.4)./6.8));
dend_golomb_Kdr_taun = @(dend_v) (0.087+11.4./(1+exp((dend_v+14.6)./8.6))) .* (0.087+11.4./(1+exp(-(dend_v-1.3)./18.7)));
dend_golomb_Kdr_ikdr = @(dend_v,dend_golomb_Kdr_n) (22.5).*(dend_golomb_Kdr_n.^2).*(dend_v-(-90));
dend_golomb_Na_minf = @(dend_v) 1./(1+exp(-(dend_v-(-24))./11.5));
dend_golomb_Na_hinf = @(dend_v) 1./(1+exp(-(dend_v+58.3)./-6.7));
dend_golomb_Na_tauh = @(dend_v) 0.5 + 14./(1+exp(-(dend_v+60)./-12));
dend_golomb_Na_ina = @(dend_v,dend_golomb_Na_h) (11.25).*dend_golomb_Na_h.*((1./(1+exp(-(dend_v-(-24))./11.5))).^3).*(dend_v-(50));
dend_input_I = @(t) 0;
dend_leak_ileak = @(dend_v) (0.03)*(dend_v-(-54.4));
dend_iMultiPoissonExp_Gte = @(t) (1).*dend_iMultiPoissonExp_Ge(:, max(1,round(t/(0.005))));
dend_iMultiPoissonExp_Itrain_e = @(dend_v,t) ((1).*dend_iMultiPoissonExp_Ge(:, max(1,round(t/(0.005))))).*(dend_v - (0));
dend_iMultiPoissonExp_Gti = @(t) (1).*dend_iMultiPoissonExp_Gi(:, max(1,round(t/(0.005))));
dend_iMultiPoissonExp_Itrain_i = @(dend_v,t) ((1).*dend_iMultiPoissonExp_Gi(:, max(1,round(t/(0.005))))).*(dend_v - (-85));
dend_iMultiPoissonExp_Itrain = @(dend_v,t) (((1).*dend_iMultiPoissonExp_Ge(:, max(1,round(t/(0.005))))).*(dend_v - (0))) + (((1).*dend_iMultiPoissonExp_Gi(:, max(1,round(t/(0.005))))).*(dend_v - (-85)));
soma_dend_iCOM_dV = @(IN,OUT) ((IN*ones(1,size(IN,1)))'-(OUT*ones(1,size(OUT,1))));
soma_dend_iCOM_ICOM = @(IN,OUT) (0.15).*sum((((IN*ones(1,size(IN,1)))'-(OUT*ones(1,size(OUT,1))))).*soma_dend_iCOM_compcon,2);
dend_dend_iGAP_IGAP = @(V1,V2) (0).*sum(((V1*ones(1,size(V1,1)))'-(V2*ones(1,size(V2,1)))).*dend_dend_iGAP_mask,2);
soma_v = zeros(2,nstep);
soma_v(:,1) = [0  0];
soma_golomb_K_a = zeros(2,nstep);
soma_golomb_K_a(:,1) = [0.5         0.5];
soma_golomb_K_b = zeros(2,nstep);
soma_golomb_K_b(:,1) = [0.5         0.5];
soma_golomb_Kdr_n = zeros(2,nstep);
soma_golomb_Kdr_n(:,1) = [0.5         0.5];
soma_golomb_Na_h = zeros(2,nstep);
soma_golomb_Na_h(:,1) = [0.5         0.5];
soma_soma_iSYN_s = zeros(2,nstep);
soma_soma_iSYN_s(:,1) = [0.1         0.1];
dend_v = zeros(2,nstep);
dend_v(:,1) = [0  0];
dend_golomb_K_a = zeros(2,nstep);
dend_golomb_K_a(:,1) = [0.5         0.5];
dend_golomb_K_b = zeros(2,nstep);
dend_golomb_K_b(:,1) = [0.5         0.5];
dend_golomb_Kdr_n = zeros(2,nstep);
dend_golomb_Kdr_n(:,1) = [0.5         0.5];
dend_golomb_Na_h = zeros(2,nstep);
dend_golomb_Na_h(:,1) = [0.5         0.5];
tstart = tic;
for k=2:nstep
  t=T(k-1);
  F=((-((1.8).*(soma_golomb_K_a(:,k-1).^3).*soma_golomb_K_b(:,k-1).*(soma_v(:,k-1)-(-90))))+((-((225).*(soma_golomb_Kdr_n(:,k-1).^2).*(soma_v(:,k-1)-(-90))))+((-((112.5).*soma_golomb_Na_h(:,k-1).*((1./(1+exp(-(soma_v(:,k-1)-(-24))./11.5))).^3).*(soma_v(:,k-1)-(50))))+((-((0.03)*(soma_v(:,k-1)-(-54.4))))+((-(((0.5).*(soma_soma_iSYN_netcon*soma_soma_iSYN_s(:,k-1)).*(soma_v(:,k-1)-(0)))))+((((0.15).*sum((((dend_v(:,k-1)*ones(1,size(dend_v(:,k-1),1)))'-(soma_v(:,k-1)*ones(1,size(soma_v(:,k-1),1))))).*dend_soma_iCOM_compcon,2)))+0))))));
  soma_v(:,k) = soma_v(:,k-1) + dt*F;
  F=((1./(1+exp(-(soma_v(:,k-1)+50)./20)))-soma_golomb_K_a(:,k-1))./2;
  soma_golomb_K_a(:,k) = soma_golomb_K_a(:,k-1) + dt*F;
  F=((1./(1+exp(-(soma_v(:,k-1)+70)./-6)))-soma_golomb_K_b(:,k-1))./150;
  soma_golomb_K_b(:,k) = soma_golomb_K_b(:,k-1) + dt*F;
  F=((1./(1+exp(-(soma_v(:,k-1)+12.4)./6.8)))-soma_golomb_Kdr_n(:,k-1))./((0.087+11.4./(1+exp((soma_v(:,k-1)+14.6)./8.6))) .* (0.087+11.4./(1+exp(-(soma_v(:,k-1)-1.3)./18.7))));
  soma_golomb_Kdr_n(:,k) = soma_golomb_Kdr_n(:,k-1) + dt*F;
  F=((1./(1+exp(-(soma_v(:,k-1)+58.3)./-6.7)))-soma_golomb_Na_h(:,k-1))./(0.5 + 14./(1+exp(-(soma_v(:,k-1)+60)./-12)));
  soma_golomb_Na_h(:,k) = soma_golomb_Na_h(:,k-1) + dt*F;
  F=-soma_soma_iSYN_s(:,k-1)./(1) + ((1-soma_soma_iSYN_s(:,k-1))/(0.25)).*(1+tanh(soma_v(:,k-1)/10));
  soma_soma_iSYN_s(:,k) = soma_soma_iSYN_s(:,k-1) + dt*F;
  F=((-((0.18).*(dend_golomb_K_a(:,k-1).^3).*dend_golomb_K_b(:,k-1).*(dend_v(:,k-1)-(-90))))+((-((22.5).*(dend_golomb_Kdr_n(:,k-1).^2).*(dend_v(:,k-1)-(-90))))+((-((11.25).*dend_golomb_Na_h(:,k-1).*((1./(1+exp(-(dend_v(:,k-1)-(-24))./11.5))).^3).*(dend_v(:,k-1)-(50))))+(((0))+((-((0.03)*(dend_v(:,k-1)-(-54.4))))+((-((((1).*dend_iMultiPoissonExp_Ge(:, max(1,round(t/(0.005))))).*(dend_v(:,k-1) - (0))) + (((1).*dend_iMultiPoissonExp_Gi(:, max(1,round(t/(0.005))))).*(dend_v(:,k-1) - (-85)))))+((((0.15).*sum((((soma_v(:,k-1)*ones(1,size(soma_v(:,k-1),1)))'-(dend_v(:,k-1)*ones(1,size(dend_v(:,k-1),1))))).*soma_dend_iCOM_compcon,2)))+((((0).*sum(((dend_v(:,k-1)*ones(1,size(dend_v(:,k-1),1)))'-(dend_v(:,k-1)*ones(1,size(dend_v(:,k-1),1)))).*dend_dend_iGAP_mask,2)))+0))))))));
  dend_v(:,k) = dend_v(:,k-1) + dt*F;
  F=((1./(1+exp(-(dend_v(:,k-1)+50)./20)))-dend_golomb_K_a(:,k-1))./2;
  dend_golomb_K_a(:,k) = dend_golomb_K_a(:,k-1) + dt*F;
  F=((1./(1+exp(-(dend_v(:,k-1)+70)./-6)))-dend_golomb_K_b(:,k-1))./150;
  dend_golomb_K_b(:,k) = dend_golomb_K_b(:,k-1) + dt*F;
  F=((1./(1+exp(-(dend_v(:,k-1)+12.4)./6.8)))-dend_golomb_Kdr_n(:,k-1))./((0.087+11.4./(1+exp((dend_v(:,k-1)+14.6)./8.6))) .* (0.087+11.4./(1+exp(-(dend_v(:,k-1)-1.3)./18.7))));
  dend_golomb_Kdr_n(:,k) = dend_golomb_Kdr_n(:,k-1) + dt*F;
  F=((1./(1+exp(-(dend_v(:,k-1)+58.3)./-6.7)))-dend_golomb_Na_h(:,k-1))./(0.5 + 14./(1+exp(-(dend_v(:,k-1)+60)./-12)));;
  dend_golomb_Na_h(:,k) = dend_golomb_Na_h(:,k-1) + dt*F;
  if any(k == enableLog)
    elapsedTime = toc(tstart);
    elapsedTimeMinutes = floor(elapsedTime/60);
    elapsedTimeSeconds = rem(elapsedTime,60);
    if elapsedTimeMinutes
        fprintf(fileID,'Processed %g of %g ms (elapsed time: %g m %.3f s)\n',T(k),T(end),elapsedTimeMinutes,elapsedTimeSeconds);
    else
        fprintf(fileID,'Processed %g of %g ms (elapsed time: %.3f s)\n',T(k),T(end),elapsedTimeSeconds);
    end
  end
end
Y=cat(1,soma_v,soma_golomb_K_a,soma_golomb_K_b,soma_golomb_Kdr_n,soma_golomb_Na_h,soma_soma_iSYN_s,dend_v,dend_golomb_K_a,dend_golomb_K_b,dend_golomb_Kdr_n,dend_golomb_Na_h)';
