%function make_fig3_new()
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 20-Apr-2019 18:36:40

X1 = ggap;
X2 = gsyn;
X3 = tonic;
YMatrix1(:,1) = mean(ggap_gamma_stats');
YMatrix1(:,2) = mean(ggap_theta_stats');
YSD1 = zeros(size(YMatrix1));
YSD1(:,1) = std(ggap_gamma_stats');
YSD1(:,2) = std(ggap_theta_stats');
YMatrix2(:,1) = mean(gsyn_gamma_stats');
YMatrix2(:,2) = mean(gsyn_theta_stats');
YSD2(:,1) = std(gsyn_gamma_stats');
YSD2(:,2) = std(gsyn_theta_stats');
YMatrix3(:,1) = mean(tonic_gamma_stats');
YMatrix3(:,2) = mean(tonic_theta_stats');
YSD3(:,1) = std(tonic_gamma_stats');
YSD3(:,2) = std(tonic_theta_stats');
Y1 = mean(tonic_gamma_freq_stats');
Y2 = mean(tonic_theta_freq_stats');
YSD4 = std(tonic_gamma_freq_stats');
YSD4b = std(tonic_theta_freq_stats');

% Create figure
figure
% Create subplot
subplot1 = subplot(2,4,1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1(:,1),'LineWidth',2,'DisplayName','\gamma power');
errorghost(ggap_gamma_stats',X1,'b');

% Create ylabel
ylabel('Gamma spectral power');

% Create xlabel
xlabel('g_{GJ} (mS/cm^2)');
axis(subplot1,'tight');
ylim([0 0.25])
%ylim([0 0.07]);

yyaxis right
plot(X1,mean(ggap_gamma_freq_stats'),'DisplayName','\gamma freq.','LineWidth',2);
errorghost(ggap_gamma_freq_stats',X1,'r');
ylim([35 90])
legend('Location','south')

% Set the remaining axes properties
%set(subplot1,'FontSize',16);

% Create subplot
subplot2 = subplot(2,4,5);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot(X1,mean(ggap_theta_stats'),'LineWidth',2,'DisplayName','\theta power');
errorghost(ggap_theta_stats',X1,'b');
ylabel('Theta spectral power');

% Create xlabel
xlabel('g_{GJ} (mS/cm^2)');
axis(subplot2,'tight');
ylim([0 0.04])
%ylim([0 0.07]);
yyaxis right
plot(X1,mean(ggap_theta_freq_stats'),'DisplayName','\theta freq.','LineWidth',2);
errorghost(ggap_theta_freq_stats',X1,'r');
legend('Location','south')
ylim([0 10])

% Set the remaining axes properties
%set(subplot2,'FontSize',16);

% Create subplot
subplot3 = subplot(2,4,2);
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X2,YMatrix2(:,1),'LineWidth',2);
set(plot3(1),'DisplayName','\gamma Power');
errorghost(gsyn_gamma_stats',X2,'b');

% Create xlabel
xlabel('g_{GABA_a} (mS/cm^2)');
axis(subplot3,'tight');
ylim([0 0.25])
%ylim([0 0.07]);
yyaxis right
plot(X2,mean(gsyn_gamma_freq_stats'),'DisplayName','\gamma Freq.','LineWidth',2);
errorghost(gsyn_gamma_freq_stats',X2,'r');
ylim([35 90])

% Set the remaining axes properties
%set(subplot3,'FontSize',16);

% Create subplot
subplot4 = subplot(2,4,6);
hold(subplot4,'on');

% Create multiple lines using matrix input to plot
plot4 = plot(X2,YMatrix2(:,2),'LineWidth',2);
set(plot4(1),'DisplayName','\theta Power');
errorghost(gsyn_theta_stats',X2,'b');

% Create xlabel
xlabel('g_{GABA_a} (mS/cm^2)');
axis(subplot4,'tight');
%ylim([0 0.07]);
ylim([0 0.04])
yyaxis right
plot(X2,mean(gsyn_theta_freq_stats'),'DisplayName','\theta Freq.','LineWidth',2);
errorghost(gsyn_theta_freq_stats',X2,'r');
ylim([0 10])

% Set the remaining axes properties
%set(subplot4,'FontSize',16);
%legend1 = legend([plot4]);
%set(legend1,'FontSize',16,'AutoUpdate','off','Location','best');

% Create subplot
subplot5 = subplot(2,4,3);
hold(subplot5,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix3(:,1),'LineWidth',2);
set(plot1(1),'DisplayName','\gamma Power');
errorghost(tonic_gamma_stats',X3,'b');

% Create xlabel
xlabel('I_{app} (mA/cm^2)');
axis(subplot5,'tight');
%ylim([0 0.07]);
ylim([0 0.25])
% Set the remaining axes properties
%set(subplot5,'FontSize',16);

% Create plot
yyaxis right
plot(X3,Y1,'DisplayName','\gamma Freq.','LineWidth',2);
errorghost(tonic_gamma_freq_stats',X3,'r');
ylim([35 90])

% Create ylabel
ylabel('Freq. (Hz)');
%axis(subplot5,'tight');
% Set the remaining axes properties
%set(axes1,'Color','none','FontSize',16,'HitTest','off','YAxisLocation',...
%    'right');
% Create legend

% Create subplot
subplot6 = subplot(2,4,7);
hold(subplot6,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix3(:,2),'LineWidth',2);
set(plot1(1),'DisplayName','\theta Power');
errorghost(tonic_theta_stats',X3,'b');

% Create xlabel
xlabel('I_{app} (mA/cm^2)');
axis(subplot6,'tight');
ylim([0 0.04])
%ylim([0 0.07]);
% Set the remaining axes properties
%set(subplot6,'FontSize',16);

% Create plot
yyaxis right
plot(X3,Y2,'DisplayName','\theta Freq.','LineWidth',2);
errorghost(tonic_theta_freq_stats',X3,'r');

% Create ylabel
ylabel('Freq. (Hz)');
%axis(subplot6,'tight');
ylim([0 10])
% Set the remaining axes properties
%set(axes1,'Color','none','FontSize',16,'HitTest','off','YAxisLocation',...
%    'right');
% Create legend

subplot7 = subplot(2,4,[4,8]);
hold(subplot7,'on');
p1 = plot(tau_gaba,mean(ing_high_DA_gamma_freq'),'k','LineWidth',2,'DisplayName','\gamma Freq. (high DA)');
p2 = plot(tau_gaba,mean(ing_low_DA_gamma_freq'),'--k','LineWidth',2,'DisplayName','\gamma Freq. (low DA)');
xlabel('tau_{GABA_a} (mS)');

errorghost(ing_high_DA_gamma_freq',tau_gaba,'k');
errorghost(ing_low_DA_gamma_freq',tau_gaba,'k');

axis(subplot7,'tight');
ylim([35 90])
legend('Location','best')
%set(subplot7,'FontSize',16);